export const ROUTER_PATH = {
    HOME: '/home',
    STUDENTS: '/students',
    SCHOOLS: '/schools'
}

export const ACTION_TYPE = {
    SET_STUDENTS: 'SET_STUDENTS',
    UPDATE_STUDENTS: 'UPDATE_STUDENTS',
    DELETE_STUDENTS: 'DELETE_STUDENTS',
    SET_SCHOOLS: 'SET_SCHOOLS',
    UPDATE_SCHOOLS: 'UPDATE_SCHOOLS',
    DELETE_SCHOOLS: 'DELETE_SCHOOLS'
}
